###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    mysql:
      image: mysql:5.7
      container_name: activities-mysql
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: activities
        MYSQL_ROOT_PASSWORD: root
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
      expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
      volumes:
        - ./docker/my-db:/var/lib/mysql

    webserver:
      image: nginx:alpine
      container_name: activities-webserver
      working_dir: /activities
      volumes:
          - .:/activities
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"
      links:
        - php-fpm
    php-fpm:
      build: phpdocker/php-fpm
      container_name: activities-php-fpm
      working_dir: /activities
      volumes:
        - .:/activities
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
        - mysql

    activities:
      image: abh1nav/dockerui
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      links:
        - webserver

