<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'event_bus' shared service.

$this->services['event_bus'] = $instance = new \SimpleBus\SymfonyBridge\Bus\EventBus();

$instance->appendMiddleware(new \SimpleBus\Message\Bus\Middleware\FinishesHandlingMessageBeforeHandlingNext());
$instance->appendMiddleware(new \SimpleBus\Message\Subscriber\NotifiesMessageSubscribersMiddleware(new \SimpleBus\Message\Subscriber\Resolver\NameBasedMessageSubscriberResolver(new \SimpleBus\Message\Name\ClassBasedNameResolver(), new \SimpleBus\Message\CallableResolver\CallableCollection(array(), new \SimpleBus\Message\CallableResolver\ServiceLocatorAwareCallableResolver(array(0 => new \Symfony\Component\DependencyInjection\ServiceLocator(array()), 1 => 'get')))), NULL, NULL));

return $instance;
