<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\Activities\Infrastructure\Commands\setTouristActivitiesCommand' shared autowired service.

$a = new \GuzzleHttp\Client();

return $this->services['console.command.public_alias.App\Activities\Infrastructure\Commands\setTouristActivitiesCommand'] = new \App\Activities\Infrastructure\Commands\setTouristActivitiesCommand(NULL, new \App\Activities\Infrastructure\FilesReader\ActivitiesReader(new \App\Activities\Infrastructure\FilesReader\GetActivitiesFromOpenData($a), new \App\Activities\Infrastructure\FilesReader\GetActivitiesFromOpenDataLibraries($a), ($this->services['command_bus'] ?? $this->load('getCommandBusService.php'))));
