<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYCgJai7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYCgJai7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYCgJai7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYCgJai7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYCgJai7\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'YCgJai7',
    'container.build_id' => 'e33bd7a7',
    'container.build_time' => 1550613191,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYCgJai7');
